api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        json:     ['application/json']
        html:     ['text/html']
        xml:      ['application/xml', 'text/xml']
    patch_formats:
        json:     ['application/merge-patch+json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        html:     ['text/html']
        xml:      ['application/xml', 'text/xml']
    swagger:
        versions: [3]
    collection:
        pagination:
            items_per_page: 10
